### PR TITLE
fix: Convert Go regex to Rust regex

### LINKED ISSUE #75: Failing to parse valid regex
The following regex fails to parse in rust, but works with the official go parser:

```
uri=~"/v[1-9]/.*/{gid}/{uid}"
```

## Reproduce

```
use promql_parser::parser;

fn main() {
    let promql = r#"rate(http_server_requests_seconds_bucket{method="GET",status=~"2..",uri=~"/v[1-9]/.*/{gid}/{uid}",le="0.25"}[1h])"#;

    match parser::parse(promql) {
        Ok(expr) => {
            println!("Prettify:\n\n{}", expr.prettify());
            println!("AST:\n{expr:?}");
        }
        Err(info) => println!("Err: {info:?}"),
    }
}
```

```
# `Err: "illegal regex for /v[1-9]/.*/{gid}/{uid}"`
```

The same query works with in go:

```
package main

import (
	"github.com/prometheus/prometheus/promql/parser"
)

func main() {
	_, err := parser.ParseExpr(`rate(http_server_requests_seconds_bucket{method="GET",status=~"2..",uri=~"/v[1-9]/.*/{gid}/{uid}",le="0.25"}[1h])`)

	if err != nil {
		panic(err)
	}
}
```

### PR DESCRIPTION
**Pull request by fbs**
Go and Rust have some differences in their regex implementation. In Go the following is valid:

```
uri=~"/v[1-9]/.*/{gid}/{uid}"
```

Rust sees the `{gid}` as a bad repetition, it expects a range like {1,4}

```
regex parse error:
    /v[1-9]/.*/{gid}/{uid}
                ^
error: repetition quantifier expects a valid decimal
```

For it to be a valid Rust regex the opening { has to be escaped.

This change adds that escaping.

The implementation is simple, iteration + writing in a result buffer. It is probably not the best of nicest way of doing it, but it straight forward.

Fixes #75

### CODE REVIEW

**Comment by yuanbohan** [comment]
Hi, thanks for your contribution :+1: 
Could you fix the clippy error? and you can refer #77, or you can rebase the main branch after the PR #77 is merged

File: src/label/matcher.rs [hunk 1]
```diff
@@ -91,15 +91,76 @@ impl Matcher {
...
+        let mut result = String::new();
+        let mut chars = re.chars();
+
+        while let Some(c) = chars.next() {
+            if c != '{' {
+                result.push(c);
+            }
+
+            // if escaping, just push the next char as well
+            if c == '\\' {
```
Comment (yuanbohan) [inline src/label/matcher.rs:133]: If `c == '\\'` branch is placed under `if c != '{'`, it is better for review?

File: src/label/matcher.rs [hunk 2]
```diff
@@ -465,4 +526,22 @@ mod tests {
...
+        assert_eq!(convert("abc{1,}"), "abc{1,}");
+        assert_eq!(convert("abc{1,2}"), "abc{1,2}");
+        assert_eq!(convert("abc{,2}"), r#"abc\{,2}"#);
+        assert_eq!(convert("abc{{1,2}}"), r#"abc\{{1,2}}"#);
+        assert_eq!(convert(r#"abc\{abc"#), r#"abc\{abc"#);
+        assert_eq!(convert("abc{1a}"), r#"abc\{1a}"#);
+        assert_eq!(convert("abc{1,a}"), r#"abc\{1,a}"#);
+        assert_eq!(convert("abc{1,2a}"), r#"abc\{1,2a}"#);
+        assert_eq!(convert("abc{1,2,3}"), r#"abc\{1,2,3}"#);
+        assert_eq!(convert("abc{1,,2}"), r#"abc\{1,,2}"#);
```
Comment (yuanbohan) [inline src/label/matcher.rs:545]: what about `abc{}`?

File: src/label/matcher.rs [hunk 3]
```diff
@@ -91,15 +91,76 @@ impl Matcher {
...
+        // (true, string) if its a valid repeat pattern (e.g. 1,2 or ,3)
+        fn is_repeat(chars: &mut std::str::Chars<'_>) -> (bool, String) {
+            let mut buf = String::new();
+            let mut comma = false;
+            while let Some(c) = chars.next() {
+                buf.push(c);
+
+                if c == ',' {
+                    // two commas or {, are both invalid
+                    if comma || buf.len() == 1 {
```
Comment (yuanbohan) [inline src/label/matcher.rs:108]: maybe `buf == ","` is easier for understanding than `len == 1`?

File: src/label/matcher.rs [hunk 4]
```diff
@@ -91,15 +91,76 @@ impl Matcher {
         }
     }
 
+    // Go and Rust handle the repeat pattern differently
+    // in Go the following is valid: `aaa{bbb}ccc`
+    // in Rust {bbb} is seen as an invalid repeat and must be ecaped \{bbb}
+    // This escapes the opening { if its not followed by valid repeat pattern (e.g. 4,6).
+    fn convert_re(re: &str) -> String {
+        // (true, string) if its a valid repeat pattern (e.g. 1,2 or ,3)
```
Comment (yuanbohan) [inline src/label/matcher.rs:99]: `,3` is not repeat?

File: src/label/matcher.rs [hunk 5]
```diff
@@ -91,15 +91,76 @@ impl Matcher {
...
+        fn is_repeat(chars: &mut std::str::Chars<'_>) -> (bool, String) {
```
Comment (yuanbohan) [inline src/label/matcher.rs:100]: In other words, only `{\d+,\d+}` is repetition, otherwise return false?

**Review by yuanbohan — CHANGES_REQUESTED** [review]

File: src/label/matcher.rs (hunk 2 above)
Comment (fbs) [reply src/label/matcher.rs:545]: ah good one

File: src/label/matcher.rs (hunk 1 above)
Comment (fbs) [reply src/label/matcher.rs:137]: not sure if it is, but can do it if you prefer

**Review by yuanbohan — APPROVED** [review]

**Comment by v0y4g3r** [comment]
Looks like we only need to convert the `{` characters without preceding  backslash `\` to `\{` while remove the preceding `\` from `\{` in Golang regex to make it work in Rust regex. 

The problem is the difference between Go and Rust in handling repetition sequence and bracket literal. Go treats `{` as 
bracket literal while Rust treats `{` as the start of repetition sequence.

For example, for `/v[1-9]/.*/{gid}/{uid}` in Golang, the corresponding Rust regex would be `/v[1-9]/.*/\{gid\}/\{uid\}`: https://regex101.com/r/k7b6N8/1

**Comment by fbs** [comment]
Yes thats basically what this MR does, Go 'auto escapes' the sequence while Rust doesn't. So the conversion is `a{aa}` -> `a\{aa}` but `a{1,2}` stays `a{1,2}`

**Comment by waynexia** [comment]
> Yes thats basically what this MR does, Go 'auto escapes' the sequence while Rust doesn't. So the conversion is `a{aa}` -> `a\{aa}` but `a{1,2}` stays `a{1,2}`

Should `a{aa}` goes to `a\{aa\}`? `}` needs escaping as well.

**Comment by yuanbohan** [comment]
> > Yes thats basically what this MR does, Go 'auto escapes' the sequence while Rust doesn't. So the conversion is `a{aa}` -> `a\{aa}` but `a{1,2}` stays `a{1,2}`
> 
> Should `a{aa}` goes to `a\{aa\}`? `}` needs escaping as well.

I'm interested in the escaping of `}`, maybe it does not affect the result if the regex does not find the starting of repetition pattern?

**Comment by fbs** [comment]
I'm not entirely sure what you mean. In my testing just escaping the `{` is enough. A `}` without leading (or with escaped) `{` is just seen as a literal


```
$ cat src/main.rs
use regex::Regex;

fn main() {
    let re = Regex::new(r"a}a\{a}").unwrap();
    let Some(caps) = re.captures("a}a{a}") else {
        println!("no match!");
        return;
    };
    println!("The name is: {:?}", caps);
}

/tmp/regex master[?] $ cargo r
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/regexxx`
The name is: Captures({0: 0..6/"a}a{a}"})
```

**Comment by waynexia** [comment]
Thanks for your contribution @fbs :heart:

**Comment by fbs** [comment]
Thanks for the quick review team! <3. 

I wonder if there are more regex incompatibility issues in this.

**Comment by yuanbohan** [comment]
> Thanks for the quick review team! <3. 
> 
> I wonder if there are more regex incompatibility issues in this. 

I will watch on this, thanks for your contribution 😀
